<?php

/**
 * @file
 * View Marquee Views module help and theme functions.
 */

// Store View Marquee preprocess theme functions in a separate .inc file.
\Drupal::moduleHandler()->loadInclude('view_marquee', 'inc', 'view-marquee.theme');

/**
 * Implements hook_theme().
 */
function view_marquee_theme($existing, $type, $theme, $path) {
  return [
    'view_marquee' => [
      'file' => 'view-marquee.theme.inc',
    ],
  ];
}
