<?php

/**
 * @file
 * Testing Slick.
 */

/**
 * Implements hook_theme().
 */
function slick_test_theme() {
  return ['slick_test' => ['render element' => 'element']];
}

/**
 * Prepares variables for slick-test.html.twig templates.
 */
function template_preprocess_slick_test(&$variables) {
  $element = $variables['element'];

  $variables['content'] = $element['#children'];
  $variables['settings'] = isset($element['#settings']) ? $element['#settings'] : [];
}
